### ISSUE TITLE
Planned features checklist

### ISSUE THREAD

**Issue by Visual-Vincent** [Visual-Vincent/GuiStack#1]
A list of planned, upcoming features. This will be updated as time goes on.

- [x] SNS support (added in [v1.1.0](https://github.com/Visual-Vincent/GuiStack/releases/tag/v1.1.0))
- [x] Ability to send messages to SNS topics, just like with SQS (added in [v1.2.0](https://github.com/Visual-Vincent/GuiStack/releases/tag/v1.2.0))
- [ ] Rebuild entire frontend in SvelteKit
- [ ] DynamoDB support
- [ ] [SQS] Option to automatically format retrieved JSON messages
- [ ] If possible: Local fallback of Monaco Editor scripts in case unpkg is down
    - [ ] Local copy of all third-party scripts to allow GuiStack to run completely offline
- [ ] Secrets Manager support

Feel free to comment below (or create another issue) with suggestions of new features!

**Comment by unconditional** [comment]
It would be great to have a UI for the API GW as well.

**Comment by Visual-Vincent** [comment]
@unconditional Thank you for the suggestion! API Gateway is a complicated beast and one that I do not yet have experience with running locally, only in the cloud. So while it is currently not on the radar, I will update the issue if this changes in the future.

PRs are also welcome if anyone would like to assist with the implementation, whether they're full-stack or a single side (back-/frontend)
